<div class="dialog">
<div class="text">Kara-Tur. Historia nawi±zuj±ca do mrocznego ¶wiata Dungeons &amp; Dragons. Tworzona przez nas - zwyk³ych graczy, którzy swoj± fantazj± potrafi± stworzyæ nowe Krainy, pokonaæ najstraszniejsze bestie, nawi±zaæ nowe znajomo¶ci. Ca³y ¶wiat Kara-Tur zamieszkiwany jest przez ró¿nego rodzaju istoty - zaczynaj±c od zwyk³ych Ludzi a koñcz±c na ¿±dnych ¶mierci Orkach. Ka¿dy z nas jest odpowiedzialny za umiejêtno¶æ i charakter naszego bohatera.</div>
<div class="desc">Dziewczyna wziê³a g³êboki wdech, za¶mia³a siê by po chwili kontynuowaæ opowie¶æ. Jednak nim zd±¿y³a otworzyæ usta, swoje kilka groszy zd±¿y³ wtr±ciæ pewien mê¿czyzna w czerwonej p³achcie</div>
<div class="text">Tak. Jak ju¿ wspomnia³a¶, je¶li kiedykolwiek traficie na ¦wiat Kara-Tur, na pewno zwrócicie uwagê na powi±zania tego ¦wiata, ze ¦wiatem Dungeons &amp; Dragons. Ale to ju¿ swoj± drog±. </div>
<div class="desc">Mê¿czyzna wsta³ i zrzuci³ w ty³ kaptur. Co¶ dziwnego wstrz±snê³o dziewczyn±, która do tego momentu siedzia³a niewzruszona przys³uchuj±c siê uwa¿nie jego s³owom. Twarz jego by³a delikatnie zabarwiona niebieskim odcieniem. Tu i ówdzie widaæ by³o kilka zgrubieñ na skórze, niczym pozosta³o¶ci po twardej skorupie. D³ugie, bia³e w³osy opad³y na ramiona, a szalone, czerwone oczy zdawa³y siê kryæ w sobie wszelkie Tajemnice o ca³ym ¦wiecie. </div>
<div class="text">Ty... Ty... ? szepnê³a. ? To Ty jeste¶ tym zbieg³ym Smokokrwistym, o którym s³ysza³ ju¿ ca³y ¦wiat?! </div>
<div class="text">Tak, moja droga. Nawet nie wiesz ile kosztowa³o mnie przedostanie siê za granice naszej kochanej stolicy Athkatli. A co dopiero wydostanie siê z lochów...</div>
<div class="desc">Zamy¶li³ siê i podpar³ plecami o pobliskie drzewo.</div>
<div class="text">Có¿. Ty tak¿e nie jeste¶ lepsza. Nimfy o tej porze roku uganiaj± siê za 'p³ci± przeciwn±', a Ty zabra³a¶ siê za opowiadania. Pomy¶l o swym losie, i pozwól, ¿e ja to dokoñczê.</div>
<div class="desc">U¶miechn±³ siê i spojrza³ w dal.</div>
<div class="text">A wiêc, Kara-Tur to opowie¶æ nas samych i o nas samych. To my j± tworzymy i my j± niszczymy. Ka¿dy z nas jest odpowiedzialny wy³±cznie za samego siebie, wcielamy siê w ¿ycie naszego Bohatera i tym¿e Bohaterem powoli siê stajemy. Do wyboru mamy klika miejsc, ró¿ni±ce siê od siebie wieloma cechami. Tak na przyk³ad: wspomniana ju¿ stolica - Athkatla ? przede wszystkim jest to stolica Amnu - jednego z faeruñskich królestw, wielka Metropolia w której spotkaæ mo¿na ka¿d± rasê, Chmurne Szczyty ? jedyne co tam siê znajduje to stara, opuszczona kopalnia, Wê¿owy Las czy Crimmor ? miasto podró¿ników, ostoja dla zmêczonych wieczn± wêdrówk±. Nie dziwiæ siê, bo i warto napomnieæ o znajduj±cym siê w nim Domu Pokus... ? nieznacznie siê u¶miechn±³ i  spojrza³ na dziewczynê.</div>
<div class="text">Kontynuuj, proszê</div>
<div class="desc">Odburknê³a i rzuci³a okiem w stronê zachodz±cego S³oñca.</div>
<div class="text">Hm. S³oñce jest dzi¶ wyj±tkowo piêkne. Ale nie to powinno nas interesowaæ. Bowiem ca³y ¦wiat jest piêknem niedostrzegalnym przez zwyk³ego cz³owieka. Bo to nie sam cz³owiek, a Bohater tylko ma prawo dojrzeæ piêkno tego ¦wiata. Czêsto schowane pod os³on± Dnia i Nocy, S³oñca i Ksiê¿yca, Morderstwa i ¯ycia. Nie mo¿na przej¶æ obojêtnie obok ¦wiata Kara-Tur. To Ty utrzymujesz ten ¶wiat przy ¿yciu. Dziêki Tobie mo¿emy funkcjonowaæ, oddychaæ, ¿yæ... Ka¿dy Cz³owiek, czy te¿ nazwê go tutaj Graczem, jest nasz± nadziej±. Nadziej±, ¿e to on w³a¶nie bêdzie w stanie kiedy¶ wstrz±sn±æ ca³ym Kara-Tur, wnie¶æ w ¿ycie ka¿dego Bohatera istotne zmiany, na lepsze, b±d¼ gorsze. Zale¿y to od nas samych. </div>
<div class="desc">Po tych s³owach zapad³a cisza. Dziewczyna wymieni³a z nim spojrzenie, i trwaj±c tak przez chwilê nie spuszczali z siebie wzroku. W koñcu Smokokrwisty odetchn±³ z ulg±, z wyra¼n± satysfakcj± i¿ skoñczy³ swój "wyk³ad". Zaci±gn±³ z powrotem kaptur, odwróci³ siê i znikn±³. Rozmy³ siê ot tak, po prostu. Po mê¿czy¼nie nie by³o ¶ladu. Zdziwiona Hobbitka wsta³a i spu¶ci³a wzrok na dó³. </div>
<div class="text" style="font-weight:bold">Tak wiêc, liczymy na Ciebie, drogi Cz³owiecze. Twój jeden Bohater, Twój jeden ruch... mo¿e ocaliæ ten ¦wiat przed zag³ad±. Nie jeste¶ nawet ¶wiadom tego, co mo¿esz dla Nas zrobiæ, wkraczaj±c na tereny Kara-Tur.</div>
<div class="desc">Dziewczyna ujê³a w d³oñ drewnian± laskê i podpieraj±c siê na niej powêdrowa³a przed siebie,  w stronê Zachodz±cego S³oñca...</div>
</div>